name: flutter_use
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# flutter build web --web-renderer html
# The following adds the Cupertino Icons font to your application.
# Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
# getx 状态管理框架 https://pub.flutter-io.cn/packages/get
  get: 4.6.5
# 状态管理框架 https://pub.dev/packages/flutter_bloc
  flutter_bloc:
# 状态管理框架 https://pub.dev/packages/provider
  provider:
# 网络请求 https://pub.flutter-io.cn/packages/dio
  dio:
# https://pub.flutter-io.cn/packages/logger
  logger:
# 时间滚轮选择器 https://pub.dev/packages/flutter_picker
  flutter_picker:
# 图片选择器 https://pub.dev/packages/wechat_assets_picker
#  wechat_assets_picker: 7.3.2
# 预览图片 https://pub.dev/packages/photo_view
  photo_view:
# iOS数字键盘添加收起按钮 https://pub.dev/packages/keyboard_actions
  keyboard_actions:
# 用于处理widget是否可见检测 https://pub.flutter-io.cn/packages/visibility_detector
  visibility_detector:
# 本地缓存 https://pub.flutter-io.cn/packages/shared_preferences
  shared_preferences:
# 轮播图: https://pub.dev/packages/card_swiper
  card_swiper:
# 设置桌面端: https://pub.dev/packages/window_manager
  window_manager: 0.2.8
# 弹窗控件 https://github.com/CNAD666/flutter_smart_dialog
  flutter_smart_dialog: 4.7.1
#  flutter_smart_dialog:
#    path: ../flutter_smart_dialog
#    flutter_smart_dialog:
  #    git:
  #      url: git://github.com/CNAD666/flutter_smart_dialog.git
  #  flutter_smart_dialog:
  #    path: F:\GitHub\flutter_smart_dialog
  # flutter_lints库：https://pub.dev/packages/flutter_lints
  flutter_lints: ^1.0.4

#  flutter_boost:
#    git:
#      url: 'https://github.com/alibaba/flutter_boost.git'
#      ref: 'v3.0-null-safety-release.2'

  # windows打包 https://pub.dev/packages/msix
  # flutter build windows
  # flutter pub run msix:create
#  msix: 3.7.0
#msix_config:
#  display_name: flutter use
#  publisher_display_name: xdd666
#  publisher: 小呆呆666
#  identity_name: xdd666.flutter.use
#  msix_version: 1.7.0.0
#  logo_path: images/icon.png
#  capabilities: "internetClient,location,microphone,webcam"
#  output_path: build/app_release
#  output_name: flutter_use(v1.7)
dependency_overrides:
  path: ^1.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
#  assets:
#    - images/icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
